@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.cookiejar.skinned_lanterns.common.block;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;