package com.github.nuxnux.skinnedlanterns.registry;

import com.github.nuxnux.skinnedlanterns.SkinnedLanterns;
import com.github.nuxnux.skinnedlanterns.blocks.SkinnedLanternBlock;
import net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.fabricmc.fabric.api.tool.attribute.v1.FabricToolTags;
import net.fabricmc.loader.FabricLoader;
import net.minecraft.block.Material;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class SkinnedLanternBlocks {

    public static final ItemGroup MORELANTERNSTAB = FabricItemGroupBuilder.build(new Identifier(SkinnedLanterns.MODID, "morelanternstab"), () -> new ItemStack(SkinnedLanternBlocks.PUFFERFISH_LANTERN_BLOCK));

    public static final SkinnedLanternBlock PUFFERFISH_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PUFFERFISH_LANTERN_BLOCK_ITEM = new BlockItem(PUFFERFISH_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PUFFERFISH_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PUFFERFISH_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PUFFERFISH_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ZOMBIE_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item ZOMBIE_LANTERN_BLOCK_ITEM = new BlockItem(ZOMBIE_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ZOMBIE_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item ZOMBIE_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(ZOMBIE_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock CREEPER_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item CREEPER_LANTERN_BLOCK_ITEM = new BlockItem(CREEPER_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock CREEPER_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item CREEPER_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(CREEPER_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock SKELETON_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item SKELETON_LANTERN_BLOCK_ITEM = new BlockItem(SKELETON_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock SKELETON_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item SKELETON_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(SKELETON_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock WITHER_SKELETON_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item WITHER_SKELETON_LANTERN_BLOCK_ITEM = new BlockItem(WITHER_SKELETON_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock WITHER_SKELETON_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item WITHER_SKELETON_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(WITHER_SKELETON_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock BEE_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item BEE_LANTERN_BLOCK_ITEM = new BlockItem(BEE_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock BEE_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item BEE_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(BEE_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock JACK_O_LANTERN_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item JACK_O_LANTERN_LANTERN_BLOCK_ITEM = new BlockItem(JACK_O_LANTERN_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock JACK_O_LANTERN_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item JACK_O_LANTERN_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(JACK_O_LANTERN_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_WHITE_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PAPER_WHITE_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_WHITE_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_WHITE_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PAPER_WHITE_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_WHITE_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock GHOST_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item GHOST_LANTERN_BLOCK_ITEM = new BlockItem(GHOST_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock GHOST_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item GHOST_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(GHOST_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock BLINKY_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item BLINKY_LANTERN_BLOCK_ITEM = new BlockItem(BLINKY_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock BLINKY_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item BLINKY_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(BLINKY_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PINKY_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PINKY_LANTERN_BLOCK_ITEM = new BlockItem(PINKY_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PINKY_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PINKY_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PINKY_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock INKY_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item INKY_LANTERN_BLOCK_ITEM = new BlockItem(INKY_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock INKY_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item INKY_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(INKY_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock CLYDE_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item CLYDE_LANTERN_BLOCK_ITEM = new BlockItem(CLYDE_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock CLYDE_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item CLYDE_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(CLYDE_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PACMAN_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PACMAN_LANTERN_BLOCK_ITEM = new BlockItem(PACMAN_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PACMAN_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PACMAN_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PACMAN_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock GUARDIAN_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item GUARDIAN_LANTERN_BLOCK_ITEM = new BlockItem(GUARDIAN_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock GUARDIAN_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item GUARDIAN_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(GUARDIAN_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_YELLOW_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PAPER_YELLOW_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_YELLOW_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_YELLOW_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PAPER_YELLOW_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_YELLOW_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_ORANGE_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PAPER_ORANGE_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_ORANGE_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_ORANGE_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PAPER_ORANGE_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_ORANGE_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_BLUE_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PAPER_BLUE_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_BLUE_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_BLUE_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PAPER_BLUE_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_BLUE_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_LIGHT_BLUE_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PAPER_LIGHT_BLUE_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_LIGHT_BLUE_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_LIGHT_BLUE_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PAPER_LIGHT_BLUE_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_LIGHT_BLUE_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_CYAN_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PAPER_CYAN_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_CYAN_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_CYAN_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PAPER_CYAN_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_CYAN_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_LIME_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PAPER_LIME_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_LIME_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_LIME_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PAPER_LIME_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_LIME_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_GREEN_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PAPER_GREEN_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_GREEN_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_GREEN_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PAPER_GREEN_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_GREEN_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PAPER_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PAPER_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_PINK_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PAPER_PINK_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_PINK_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_PINK_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PAPER_PINK_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_PINK_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_BROWN_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PAPER_BROWN_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_BROWN_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_BROWN_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PAPER_BROWN_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_BROWN_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_BLACK_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PAPER_BLACK_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_BLACK_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_BLACK_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PAPER_BLACK_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_BLACK_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_GRAY_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PAPER_GRAY_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_GRAY_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_GRAY_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PAPER_GRAY_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_GRAY_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_LIGHT_GRAY_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PAPER_LIGHT_GRAY_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_LIGHT_GRAY_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_LIGHT_GRAY_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PAPER_LIGHT_GRAY_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_LIGHT_GRAY_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_MAGENTA_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PAPER_MAGENTA_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_MAGENTA_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_MAGENTA_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PAPER_MAGENTA_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_MAGENTA_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_PURPLE_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PAPER_PURPLE_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_PURPLE_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PAPER_PURPLE_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PAPER_PURPLE_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PAPER_PURPLE_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));

    public static final SkinnedLanternBlock ORNAMENT_RED_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item ORNAMENT_RED_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_RED_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_RED_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item ORNAMENT_RED_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_RED_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_BLUE_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item ORNAMENT_BLUE_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_BLUE_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_BLUE_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item ORNAMENT_BLUE_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_BLUE_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_PURPLE_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item ORNAMENT_PURPLE_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_PURPLE_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_PURPLE_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item ORNAMENT_PURPLE_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_PURPLE_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_LIME_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item ORNAMENT_LIME_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_LIME_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_LIME_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item ORNAMENT_LIME_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_LIME_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_MAGENTA_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item ORNAMENT_MAGENTA_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_MAGENTA_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_MAGENTA_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item ORNAMENT_MAGENTA_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_MAGENTA_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_YELLOW_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item ORNAMENT_YELLOW_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_YELLOW_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_YELLOW_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item ORNAMENT_YELLOW_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_YELLOW_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_GREEN_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item ORNAMENT_GREEN_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_GREEN_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_GREEN_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item ORNAMENT_GREEN_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_GREEN_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_LIGHT_BLUE_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item ORNAMENT_LIGHT_BLUE_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_LIGHT_BLUE_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_LIGHT_BLUE_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item ORNAMENT_LIGHT_BLUE_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_LIGHT_BLUE_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_CYAN_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item ORNAMENT_CYAN_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_CYAN_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_CYAN_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item ORNAMENT_CYAN_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_CYAN_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_PINK_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item ORNAMENT_PINK_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_PINK_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_PINK_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item ORNAMENT_PINK_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_PINK_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_ORANGE_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item ORNAMENT_ORANGE_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_ORANGE_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_ORANGE_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item ORNAMENT_ORANGE_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_ORANGE_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_BROWN_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item ORNAMENT_BROWN_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_BROWN_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_BROWN_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item ORNAMENT_BROWN_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_BROWN_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_BLACK_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item ORNAMENT_BLACK_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_BLACK_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_BLACK_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item ORNAMENT_BLACK_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_BLACK_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_WHITE_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item ORNAMENT_WHITE_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_WHITE_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_WHITE_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item ORNAMENT_WHITE_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_WHITE_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_GRAY_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item ORNAMENT_GRAY_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_GRAY_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_GRAY_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item ORNAMENT_GRAY_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_GRAY_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_LIGHT_GRAY_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item ORNAMENT_LIGHT_GRAY_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_LIGHT_GRAY_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock ORNAMENT_LIGHT_GRAY_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item ORNAMENT_LIGHT_GRAY_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(ORNAMENT_LIGHT_GRAY_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PRESENT_GREEN_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PRESENT_GREEN_LANTERN_BLOCK_ITEM = new BlockItem(PRESENT_GREEN_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PRESENT_GREEN_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PRESENT_GREEN_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PRESENT_GREEN_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PRESENT_RED_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item PRESENT_RED_LANTERN_BLOCK_ITEM = new BlockItem(PRESENT_RED_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock PRESENT_RED_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item PRESENT_RED_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(PRESENT_RED_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock SNOWMAN_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item SNOWMAN_LANTERN_BLOCK_ITEM = new BlockItem(SNOWMAN_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock SNOWMAN_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item SNOWMAN_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(SNOWMAN_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));

    public static final SkinnedLanternBlock JELLYFISH_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item JELLYFISH_LANTERN_BLOCK_ITEM = new BlockItem(JELLYFISH_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock JELLYFISH_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item JELLYFISH_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(JELLYFISH_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock BLUE_JELLYFISH_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item BLUE_JELLYFISH_LANTERN_BLOCK_ITEM = new BlockItem(BLUE_JELLYFISH_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock BLUE_JELLYFISH_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item BLUE_JELLYFISH_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(BLUE_JELLYFISH_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));

    public static final SkinnedLanternBlock LIL_TATER_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item LIL_TATER_LANTERN_BLOCK_ITEM = new BlockItem(LIL_TATER_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock LIL_TATER_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item LIL_TATER_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(LIL_TATER_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));

    public static final SkinnedLanternBlock HONEY_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item HONEY_LANTERN_BLOCK_ITEM = new BlockItem(HONEY_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock HONEY_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item HONEY_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(HONEY_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock SLIME_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.LANTERN);
    public static final Item SLIME_LANTERN_BLOCK_ITEM = new BlockItem(SLIME_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    public static final SkinnedLanternBlock SLIME_SOUL_LANTERN_BLOCK = new SkinnedLanternBlock(Properties.SOUL_LANTERN);
    public static final Item SLIME_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(SLIME_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    //public static final AxolotlSkinnedLanternBlock AXOLOTL_LANTERN_BLOCK = new AxolotlSkinnedLanternBlock(Properties.LANTERN);
    //public static final Item AXOLOTL_LANTERN_BLOCK_ITEM = new BlockItem(AXOLOTL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));
    //public static final AxolotlSkinnedLanternBlock AXOLOTL_SOUL_LANTERN_BLOCK = new AxolotlSkinnedLanternBlock(Properties.SOUL_LANTERN);
    //public static final Item AXOLOTL_SOUL_LANTERN_BLOCK_ITEM = new BlockItem(AXOLOTL_SOUL_LANTERN_BLOCK, new Item.Settings().group(MORELANTERNSTAB));

    public static class Properties {

        public static final FabricBlockSettings LANTERN = FabricBlockSettings
                .of(Material.METAL)
                .hardness(3.05f)
                .resistance(3.05f)
                .breakByTool(FabricToolTags.PICKAXES)
                .sounds(BlockSoundGroup.LANTERN)
                .lightLevel(15)
                .breakByHand(false)
                .requiresTool();
        public static final FabricBlockSettings SOUL_LANTERN = FabricBlockSettings
                .of(Material.METAL)
                .hardness(3.05f)
                .resistance(3.05f)
                .breakByTool(FabricToolTags.PICKAXES)
                .sounds(BlockSoundGroup.LANTERN)
                .lightLevel(10)
                .breakByHand(false)
                .requiresTool();

    }

    public static void RegisterSkinnedLanternBlocks() {

        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "pufferfish_lantern_block"), PUFFERFISH_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "pufferfish_lantern_block"), PUFFERFISH_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "pufferfish_soul_lantern_block"), PUFFERFISH_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "pufferfish_soul_lantern_block"), PUFFERFISH_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "zombie_lantern_block"), ZOMBIE_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "zombie_lantern_block"), ZOMBIE_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "zombie_soul_lantern_block"), ZOMBIE_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "zombie_soul_lantern_block"), ZOMBIE_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "creeper_lantern_block"), CREEPER_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "creeper_lantern_block"), CREEPER_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "creeper_soul_lantern_block"), CREEPER_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "creeper_soul_lantern_block"), CREEPER_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "skeleton_lantern_block"), SKELETON_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "skeleton_lantern_block"), SKELETON_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "skeleton_soul_lantern_block"), SKELETON_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "skeleton_soul_lantern_block"), SKELETON_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "wither_skeleton_lantern_block"), WITHER_SKELETON_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "wither_skeleton_lantern_block"), WITHER_SKELETON_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "wither_skeleton_soul_lantern_block"), WITHER_SKELETON_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "wither_skeleton_soul_lantern_block"), WITHER_SKELETON_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "bee_lantern_block"), BEE_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "bee_lantern_block"), BEE_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "bee_soul_lantern_block"), BEE_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "bee_soul_lantern_block"), BEE_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "jack_o_lantern_lantern_block"), JACK_O_LANTERN_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "jack_o_lantern_lantern_block"), JACK_O_LANTERN_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "jack_o_lantern_soul_lantern_block"), JACK_O_LANTERN_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "jack_o_lantern_soul_lantern_block"), JACK_O_LANTERN_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_white_lantern_block"), PAPER_WHITE_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_white_lantern_block"), PAPER_WHITE_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_white_soul_lantern_block"), PAPER_WHITE_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_white_soul_lantern_block"), PAPER_WHITE_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ghost_lantern_block"), GHOST_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ghost_lantern_block"), GHOST_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ghost_soul_lantern_block"), GHOST_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ghost_soul_lantern_block"), GHOST_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "blinky_lantern_block"), BLINKY_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "blinky_lantern_block"), BLINKY_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "blinky_soul_lantern_block"), BLINKY_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "blinky_soul_lantern_block"), BLINKY_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "pinky_lantern_block"), PINKY_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "pinky_lantern_block"), PINKY_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "pinky_soul_lantern_block"), PINKY_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "pinky_soul_lantern_block"), PINKY_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "inky_lantern_block"), INKY_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "inky_lantern_block"), INKY_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "inky_soul_lantern_block"), INKY_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "inky_soul_lantern_block"), INKY_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "clyde_lantern_block"), CLYDE_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "clyde_lantern_block"), CLYDE_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "clyde_soul_lantern_block"), CLYDE_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "clyde_soul_lantern_block"), CLYDE_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "pacman_lantern_block"), PACMAN_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "pacman_lantern_block"), PACMAN_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "pacman_soul_lantern_block"), PACMAN_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "pacman_soul_lantern_block"), PACMAN_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "guardian_lantern_block"), GUARDIAN_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "guardian_lantern_block"), GUARDIAN_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "guardian_soul_lantern_block"), GUARDIAN_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "guardian_soul_lantern_block"), GUARDIAN_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_yellow_lantern_block"), PAPER_YELLOW_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_yellow_lantern_block"), PAPER_YELLOW_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_yellow_soul_lantern_block"), PAPER_YELLOW_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_yellow_soul_lantern_block"), PAPER_YELLOW_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_orange_lantern_block"), PAPER_ORANGE_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_orange_lantern_block"), PAPER_ORANGE_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_orange_soul_lantern_block"), PAPER_ORANGE_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_orange_soul_lantern_block"), PAPER_ORANGE_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_blue_lantern_block"), PAPER_BLUE_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_blue_lantern_block"), PAPER_BLUE_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_blue_soul_lantern_block"), PAPER_BLUE_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_blue_soul_lantern_block"), PAPER_BLUE_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_light_blue_lantern_block"), PAPER_LIGHT_BLUE_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_light_blue_lantern_block"), PAPER_LIGHT_BLUE_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_light_blue_soul_lantern_block"), PAPER_LIGHT_BLUE_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_light_blue_soul_lantern_block"), PAPER_LIGHT_BLUE_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_cyan_lantern_block"), PAPER_CYAN_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_cyan_lantern_block"), PAPER_CYAN_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_cyan_soul_lantern_block"), PAPER_CYAN_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_cyan_soul_lantern_block"), PAPER_CYAN_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_lime_lantern_block"), PAPER_LIME_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_lime_lantern_block"), PAPER_LIME_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_lime_soul_lantern_block"), PAPER_LIME_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_lime_soul_lantern_block"), PAPER_LIME_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_green_lantern_block"), PAPER_GREEN_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_green_lantern_block"), PAPER_GREEN_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_green_soul_lantern_block"), PAPER_GREEN_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_green_soul_lantern_block"), PAPER_GREEN_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_lantern_block"), PAPER_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_lantern_block"), PAPER_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_soul_lantern_block"), PAPER_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_soul_lantern_block"), PAPER_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_pink_lantern_block"), PAPER_PINK_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_pink_lantern_block"), PAPER_PINK_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_pink_soul_lantern_block"), PAPER_PINK_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_pink_soul_lantern_block"), PAPER_PINK_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_brown_lantern_block"), PAPER_BROWN_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_brown_lantern_block"), PAPER_BROWN_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_brown_soul_lantern_block"), PAPER_BROWN_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_brown_soul_lantern_block"), PAPER_BROWN_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_black_lantern_block"), PAPER_BLACK_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_black_lantern_block"), PAPER_BLACK_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_black_soul_lantern_block"), PAPER_BLACK_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_black_soul_lantern_block"), PAPER_BLACK_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_gray_lantern_block"), PAPER_GRAY_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_gray_lantern_block"), PAPER_GRAY_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_gray_soul_lantern_block"), PAPER_GRAY_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_gray_soul_lantern_block"), PAPER_GRAY_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_light_gray_lantern_block"), PAPER_LIGHT_GRAY_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_light_gray_lantern_block"), PAPER_LIGHT_GRAY_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_light_gray_soul_lantern_block"), PAPER_LIGHT_GRAY_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_light_gray_soul_lantern_block"), PAPER_LIGHT_GRAY_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_magenta_lantern_block"), PAPER_MAGENTA_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_magenta_lantern_block"), PAPER_MAGENTA_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_magenta_soul_lantern_block"), PAPER_MAGENTA_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_magenta_soul_lantern_block"), PAPER_MAGENTA_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_purple_lantern_block"), PAPER_PURPLE_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_purple_lantern_block"), PAPER_PURPLE_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "paper_purple_soul_lantern_block"), PAPER_PURPLE_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "paper_purple_soul_lantern_block"), PAPER_PURPLE_SOUL_LANTERN_BLOCK_ITEM);

        //Christmas lanterns!
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_red_lantern_block"), ORNAMENT_RED_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_red_lantern_block"), ORNAMENT_RED_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_red_soul_lantern_block"), ORNAMENT_RED_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_red_soul_lantern_block"), ORNAMENT_RED_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_blue_lantern_block"), ORNAMENT_BLUE_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_blue_lantern_block"), ORNAMENT_BLUE_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_blue_soul_lantern_block"), ORNAMENT_BLUE_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_blue_soul_lantern_block"), ORNAMENT_BLUE_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_purple_lantern_block"), ORNAMENT_PURPLE_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_purple_lantern_block"), ORNAMENT_PURPLE_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_purple_soul_lantern_block"), ORNAMENT_PURPLE_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_purple_soul_lantern_block"), ORNAMENT_PURPLE_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_lime_lantern_block"), ORNAMENT_LIME_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_lime_lantern_block"), ORNAMENT_LIME_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_lime_soul_lantern_block"), ORNAMENT_LIME_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_lime_soul_lantern_block"), ORNAMENT_LIME_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_magenta_lantern_block"), ORNAMENT_MAGENTA_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_magenta_lantern_block"), ORNAMENT_MAGENTA_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_magenta_soul_lantern_block"), ORNAMENT_MAGENTA_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_magenta_soul_lantern_block"), ORNAMENT_MAGENTA_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_yellow_lantern_block"), ORNAMENT_YELLOW_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_yellow_lantern_block"), ORNAMENT_YELLOW_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_yellow_soul_lantern_block"), ORNAMENT_YELLOW_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_yellow_soul_lantern_block"), ORNAMENT_YELLOW_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_green_lantern_block"), ORNAMENT_GREEN_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_green_lantern_block"), ORNAMENT_GREEN_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_green_soul_lantern_block"), ORNAMENT_GREEN_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_green_soul_lantern_block"), ORNAMENT_GREEN_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_light_blue_lantern_block"), ORNAMENT_LIGHT_BLUE_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_light_blue_lantern_block"), ORNAMENT_LIGHT_BLUE_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_light_blue_soul_lantern_block"), ORNAMENT_LIGHT_BLUE_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_light_blue_soul_lantern_block"), ORNAMENT_LIGHT_BLUE_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_cyan_lantern_block"), ORNAMENT_CYAN_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_cyan_lantern_block"), ORNAMENT_CYAN_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_cyan_soul_lantern_block"), ORNAMENT_CYAN_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_cyan_soul_lantern_block"), ORNAMENT_CYAN_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_pink_lantern_block"), ORNAMENT_PINK_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_pink_lantern_block"), ORNAMENT_PINK_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_pink_soul_lantern_block"), ORNAMENT_PINK_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_pink_soul_lantern_block"), ORNAMENT_PINK_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_orange_lantern_block"), ORNAMENT_ORANGE_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_orange_lantern_block"), ORNAMENT_ORANGE_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_orange_soul_lantern_block"), ORNAMENT_ORANGE_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_orange_soul_lantern_block"), ORNAMENT_ORANGE_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_brown_lantern_block"), ORNAMENT_BROWN_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_brown_lantern_block"), ORNAMENT_BROWN_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_brown_soul_lantern_block"), ORNAMENT_BROWN_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_brown_soul_lantern_block"), ORNAMENT_BROWN_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_black_lantern_block"), ORNAMENT_BLACK_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_black_lantern_block"), ORNAMENT_BLACK_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_black_soul_lantern_block"), ORNAMENT_BLACK_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_black_soul_lantern_block"), ORNAMENT_BLACK_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_white_lantern_block"), ORNAMENT_WHITE_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_white_lantern_block"), ORNAMENT_WHITE_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_white_soul_lantern_block"), ORNAMENT_WHITE_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_white_soul_lantern_block"), ORNAMENT_WHITE_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_gray_lantern_block"), ORNAMENT_GRAY_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_gray_lantern_block"), ORNAMENT_GRAY_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_gray_soul_lantern_block"), ORNAMENT_GRAY_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_gray_soul_lantern_block"), ORNAMENT_GRAY_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_light_gray_lantern_block"), ORNAMENT_LIGHT_GRAY_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_light_gray_lantern_block"), ORNAMENT_LIGHT_GRAY_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "ornament_light_gray_soul_lantern_block"), ORNAMENT_LIGHT_GRAY_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "ornament_light_gray_soul_lantern_block"), ORNAMENT_LIGHT_GRAY_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "present_green_lantern_block"), PRESENT_GREEN_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "present_green_lantern_block"), PRESENT_GREEN_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "present_green_soul_lantern_block"), PRESENT_GREEN_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "present_green_soul_lantern_block"), PRESENT_GREEN_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "present_red_lantern_block"), PRESENT_RED_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "present_red_lantern_block"), PRESENT_RED_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "present_red_soul_lantern_block"), PRESENT_RED_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "present_red_soul_lantern_block"), PRESENT_RED_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "snowman_lantern_block"), SNOWMAN_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "snowman_lantern_block"), SNOWMAN_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "snowman_soul_lantern_block"), SNOWMAN_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "snowman_soul_lantern_block"), SNOWMAN_SOUL_LANTERN_BLOCK_ITEM);

        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "jellyfish_lantern_block"), JELLYFISH_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "jellyfish_lantern_block"), JELLYFISH_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "jellyfish_soul_lantern_block"), JELLYFISH_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "jellyfish_soul_lantern_block"), JELLYFISH_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "blue_jellyfish_lantern_block"), BLUE_JELLYFISH_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "blue_jellyfish_lantern_block"), BLUE_JELLYFISH_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "blue_jellyfish_soul_lantern_block"), BLUE_JELLYFISH_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "blue_jellyfish_soul_lantern_block"), BLUE_JELLYFISH_SOUL_LANTERN_BLOCK_ITEM);

        //Lil tater reloaded compatibility
        if (FabricLoader.INSTANCE.isModLoaded("ltr")) {
            Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "lil_tater_lantern_block"), LIL_TATER_LANTERN_BLOCK);
            Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "lil_tater_lantern_block"), LIL_TATER_LANTERN_BLOCK_ITEM);
            Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "lil_tater_soul_lantern_block"), LIL_TATER_SOUL_LANTERN_BLOCK);
            Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "lil_tater_soul_lantern_block"), LIL_TATER_SOUL_LANTERN_BLOCK_ITEM);
        }

        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "honey_lantern_block"), HONEY_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "honey_lantern_block"), HONEY_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "honey_soul_lantern_block"), HONEY_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "honey_soul_lantern_block"), HONEY_SOUL_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "slime_lantern_block"), SLIME_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "slime_lantern_block"), SLIME_LANTERN_BLOCK_ITEM);
        Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "slime_soul_lantern_block"), SLIME_SOUL_LANTERN_BLOCK);
        Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "slime_soul_lantern_block"), SLIME_SOUL_LANTERN_BLOCK_ITEM);
        //Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "axolotl_lantern_block"), AXOLOTL_LANTERN_BLOCK);
        //Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "axolotl_lantern_block"), AXOLOTL_LANTERN_BLOCK_ITEM);
        //Registry.register(Registry.BLOCK, new Identifier(SkinnedLanterns.MODID, "axolotl_soul_lantern_block"), AXOLOTL_SOUL_LANTERN_BLOCK);
        //Registry.register(Registry.ITEM, new Identifier(SkinnedLanterns.MODID, "axolotl_soul_lantern_block"), AXOLOTL_SOUL_LANTERN_BLOCK_ITEM);

    }

}
